### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by Red-M** [romybompart/Adafruit_CircuitPython_MCP23Sxx#1]
Does this actually work and would you be interested to put this against a fork of the original MCP230XX library?

**Comment by romybompart** [comment]
Hi @Red-M, it works truly. I am using it on my own setup based on the MCP23S17 which uses SPI interface instead of I2C that corresponds to the MCP23017. So far I created the MCP23S17 class I haven't implemented other MCP23XX yet. Do you have a need? 

The difference between the original MCP230XX and this one is the mcp23sxx.py since it uses spi, and the mcp23s17.py constructor has a different set of instructions.

Notice: original mcp230xx.py and this one are named differently, the 0 and s denotes I2C and SPI.

I invite you to check the examples I did.. This abstractions allow everybody to transition from I2C architecture tu SPI architecture almost doing few changes in the code.

In my example examples/mcp23s17_expandable_mcp23017_cs.py you can see how I mixed the MCP23017 and the MCP23S17 in one setup. Six (6) different MCP23S17's chip select pins are controlled by a single MCP23017's (I2C). It is an interesting example.

Best Regards

**Comment by Red-M** [comment]
Thats fine, I wanted to be able to provide the wider community the option to switch between the I2C and SPI versions.
Personally I am using the SPI version because I need faster access times than the I2C version.

**Comment by romybompart** [comment]
Yes please forked and feel free to improve it.
I am using SPI because in i2C you can only have 8 of these ICs connected to a single bus of I2C.

Then I moved to SPI but I noticed Adafruit didn't have a library, So I created this one based on the same abstraction Layer.

Please it will be an honor if you use it a test it on your project. I worked for me very sweet.

**Comment by Red-M** [comment]
The only issue is that this repository isn't a fork of the
adafruit_mcp230xx lib so I can't make sure your commits are included if I
were to offer them upstream.

**Comment by romybompart** [comment]
It won't be since the MCP23S17 is SPI and the MCP23017 is I2c, we can make a new library joining both together.. And following few steps to contribute with Adafruit.. Here is the link of the steps to follow :  https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/creating-a-library

If you agree we can do it together

**Comment by Red-M** [comment]
Thats fine but I want to make sure we're retaining both your commits and any of adafruits so that the contributors of both are well known. To do that you'd need to fork their I2C repo and add your SPI version to it so that I can take the result of that work and make a combination library that works with both. All you'd have to do is make a MCP23SXX directory in the forked repository and I can take it from there.

**Comment by romybompart** [comment]
Closed due to thw merged done by Red-M
